# permissions for end users to view greatdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greatdbcluster-viewer-role
rules:
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbclusters/status
  verbs:
  - get
