# permissions for end users to edit greatdbmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greatdbmonitor-editor-role
rules:
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbmonitors/status
  verbs:
  - get
