# permissions for end users to view greatdbmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greatdbmonitor-viewer-role
rules:
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbmonitors/status
  verbs:
  - get
