# permissions for end users to edit greatdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greatdbcluster-editor-role
rules:
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wu123.com.wu123.com
  resources:
  - greatdbclusters/status
  verbs:
  - get
